set( APPLICATION_NAME       "LCSShare" )
#set( APPLICATION_SHORTNAME  ${APPLICATION_NAME} )
set( APPLICATION_EXECUTABLE "lcsshare" )
set( APPLICATION_DOMAIN     "lcs.my" )
set( APPLICATION_VENDOR     "LCS" )
set( APPLICATION_UPDATE_URL "https://update.lcs.my/lcsshare/" CACHE string "URL for updater" )

set( THEME_CLASS            "ownCloudTheme" )
set( APPLICATION_REV_DOMAIN "my.lcs.share" )
set( WIN_SETUP_BITMAP_PATH  "${CMAKE_SOURCE_DIR}/admin/win/nsi" )
# set( THEME_INCLUDE          "${OEM_THEME_DIR}/mytheme.h" )
# set( APPLICATION_LICENSE    "${OEM_THEME_DIR}/license.txt )
